// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: kjuFFTSZb8fanzCHT2C1jz
// Component: QePfxm7iE7o
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import ValuePropSection from "../../ValuePropSection"; // plasmic-import: 6Zq5_xjO9F/component
import SmallValuePropCard from "../../SmallValuePropCard"; // plasmic-import: ZsmzGgkZw2/component
import GraphicIcon from "../../GraphicIcon"; // plasmic-import: TcXkT68Mp6/component
import Linky from "../../Linky"; // plasmic-import: EDH0JqEGKc/component
import { ThemeContext } from "./PlasmicGlobalVariant__Theme"; // plasmic-import: 9MzawQbD5r/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as sty from "./PlasmicHitGroundRunningSection.module.css"; // plasmic-import: QePfxm7iE7o/css
import Icon29Icon from "./icons/PlasmicIcon__Icon29"; // plasmic-import: VwsBlWFPux/icon
import Icon20Icon from "./icons/PlasmicIcon__Icon20"; // plasmic-import: YhhYiXTtXT/icon
import Icon18Icon from "./icons/PlasmicIcon__Icon18"; // plasmic-import: qrdgDrcfzD/icon
import Icon13Icon from "./icons/PlasmicIcon__Icon13"; // plasmic-import: CyAK3Gjxwu/icon
import Icon19Icon from "./icons/PlasmicIcon__Icon19"; // plasmic-import: ymoKOCfuo-/icon
import image7RU1GD3ENw from "./images/image7.svg"; // plasmic-import: rU1g-d3eNw/picture
import montageNsQNwrjDr from "./images/montage.png"; // plasmic-import: nsQNwrjDr/picture
import publishpngMLv4CVe6I from "./images/publishpng.png"; // plasmic-import: MLv4cVE6I/picture
import image16EjT54Ab5 from "./images/image16.png"; // plasmic-import: ejT54-AB5/picture
import image404XNgS0Ykp from "./images/image40.png"; // plasmic-import: 4XNgS0YKP/picture
import designSystemFyeMyi6Nk from "./images/designSystem.png"; // plasmic-import: fyeMYI6Nk/picture

export const PlasmicHitGroundRunningSection__VariantProps = new Array();

export const PlasmicHitGroundRunningSection__ArgProps = new Array("children");

function PlasmicHitGroundRunningSection__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  const globalVariants = ensureGlobalVariants({
    theme: React.useContext(ThemeContext)
  });

  return (
    <ValuePropSection
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      actionButton={null}
      backgroundImage={
        <img
          alt={""}
          className={classNames(defaultcss.img, sty.img__ePqty)}
          role={"img"}
          src={image7RU1GD3ENw}
        />
      }
      className={classNames("__wab_instance", sty.root)}
      description={null}
      extraSlot={
        <React.Fragment>
          <SmallValuePropCard
            data-plasmic-name={"valueB1"}
            data-plasmic-override={overrides.valueB1}
            actionButton={null}
            className={classNames("__wab_instance", sty.valueB1)}
            description={
              "Or learn from our collection of example projects and tutorials. Landing pages, storefronts, portfolios, apps, and more."
            }
            followupLink={
              <Linky
                className={classNames("__wab_instance", sty.linky__jGmvE)}
                link={"https://plasmic.app/signup"}
                style={["noPadding"]}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__ymDwD
                  )}
                >
                  {"Sign up to browse starter projects ➔"}
                </div>
              </Linky>
            }
            icon={
              <GraphicIcon
                className={classNames(
                  "__wab_instance",
                  sty.graphicIcon___9Kw8Q
                )}
                colors={"lightCyanSolid"}
              >
                <Icon29Icon
                  className={classNames(defaultcss.all, sty.svg__a3P)}
                  role={"img"}
                />
              </GraphicIcon>
            }
            ltr={"ltr"}
            reverse={"reverse"}
            rightImage={"rightImage"}
            showcaseImage={
              <img
                alt={""}
                className={classNames(defaultcss.img, sty.img__kEwAg)}
                loading={"lazy"}
                role={"img"}
                src={montageNsQNwrjDr}
              />
            }
          >
            {"Grab a template and go."}
          </SmallValuePropCard>

          <SmallValuePropCard
            data-plasmic-name={"valueB42"}
            data-plasmic-override={overrides.valueB42}
            actionButton={null}
            className={classNames("__wab_instance", sty.valueB42)}
            description={
              "Deploy a complete hosted website end-to-end. Push changes directly to GitHub as PRs or commits. Or connect to your own CI/CD webhooks. And even spin up a CodeSandbox to experiment right in the browser."
            }
            followupLink={
              <Linky
                className={classNames("__wab_instance", sty.linky__fQbi)}
                link={"/learn/todomvc-tutorial/"}
                style={["noPadding"]}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__kLTg0
                  )}
                >
                  {"Learn about publishing ➔"}
                </div>
              </Linky>
            }
            icon={
              <GraphicIcon
                className={classNames("__wab_instance", sty.graphicIcon__izFq)}
                colors={"lightCyanSolid"}
              >
                <Icon20Icon
                  className={classNames(defaultcss.all, sty.svg__sfz3F)}
                  role={"img"}
                />
              </GraphicIcon>
            }
            ltr={"ltr"}
            rightImage={"rightImage"}
            showcaseImage={
              <img
                alt={""}
                className={classNames(defaultcss.img, sty.img__bWVpS)}
                loading={"lazy"}
                role={"img"}
                src={publishpngMLv4CVe6I}
              />
            }
          >
            {"Publish in one click."}
          </SmallValuePropCard>

          <SmallValuePropCard
            data-plasmic-name={"valueB2"}
            data-plasmic-override={overrides.valueB2}
            actionButton={null}
            className={classNames("__wab_instance", sty.valueB2)}
            description={
              "Move up the starting line. Let us handle all the grungy translation of vector graphics to web standards with our ultra-high-fidelity design-to-code importer. Then use Plasmic to make it production-ready."
            }
            followupLink={
              <Linky
                className={classNames("__wab_instance", sty.linky__adWb)}
                link={"/learn/importing-from-figma"}
                style={["noPadding"]}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__l9Fvf
                  )}
                >
                  {"Learn about the Figma plugin ➔"}
                </div>
              </Linky>
            }
            icon={
              <GraphicIcon
                className={classNames("__wab_instance", sty.graphicIcon__s3FBd)}
                colors={"lightCyanSolid"}
              >
                <Icon18Icon
                  className={classNames(defaultcss.all, sty.svg__nxpNo)}
                  role={"img"}
                />
              </GraphicIcon>
            }
            ltr={"ltr"}
            reverse={"reverse"}
            rightImage={"rightImage"}
            showcaseImage={
              <img
                alt={""}
                className={classNames(defaultcss.img, sty.img__gHw2R)}
                loading={"lazy"}
                role={"img"}
                src={image16EjT54Ab5}
              />
            }
          >
            {"Import from Figma."}
          </SmallValuePropCard>

          <SmallValuePropCard
            data-plasmic-name={"valueB4"}
            data-plasmic-override={overrides.valueB4}
            actionButton={null}
            className={classNames("__wab_instance", sty.valueB4)}
            description={p.renderPlasmicSlot({
              defaultContents:
                "Starting on something new? Generate a full Next.js site from scratch.",
              value: args.children
            })}
            followupLink={
              <Linky
                className={classNames("__wab_instance", sty.linky__vYnch)}
                link={"/learn/quickstart/"}
                style={["noPadding"]}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__ejkN
                  )}
                >
                  {"Developer quickstart ➔"}
                </div>
              </Linky>
            }
            icon={
              <GraphicIcon
                className={classNames(
                  "__wab_instance",
                  sty.graphicIcon___6W0Yy
                )}
                colors={"lightCyanSolid"}
              >
                <Icon13Icon
                  className={classNames(defaultcss.all, sty.svg___6JVb8)}
                  role={"img"}
                />
              </GraphicIcon>
            }
            ltr={"ltr"}
            rightImage={"rightImage"}
            showcaseImage={
              <img
                alt={""}
                className={classNames(defaultcss.img, sty.img__umMsq)}
                loading={"lazy"}
                role={"img"}
                src={image404XNgS0Ykp}
              />
            }
          >
            {"Generate a full codebase."}
          </SmallValuePropCard>

          <SmallValuePropCard
            data-plasmic-name={"valueB3"}
            data-plasmic-override={overrides.valueB3}
            actionButton={null}
            className={classNames("__wab_instance", sty.valueB3)}
            description={
              <span>
                <React.Fragment>
                  {"Go beyond theming and create fully accessible, "}
                </React.Fragment>
                <span style={{ fontWeight: 700 }}>{"bespoke"}</span>
                <React.Fragment>
                  {
                    " design systems without a single line of code, using the Plume meta design system."
                  }
                </React.Fragment>
              </span>
            }
            followupLink={
              <Linky
                className={classNames("__wab_instance", sty.linky___1WWPx)}
                link={"/learn/plume/"}
                style={["noPadding"]}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__gGdVk
                  )}
                >
                  {"Learn about Plume ➔"}
                </div>
              </Linky>
            }
            icon={
              <GraphicIcon
                className={classNames("__wab_instance", sty.graphicIcon__yGM)}
                colors={"lightCyanSolid"}
              >
                <Icon19Icon
                  className={classNames(defaultcss.all, sty.svg__ssjT6)}
                  role={"img"}
                />
              </GraphicIcon>
            }
            ltr={"ltr"}
            reverse={"reverse"}
            rightImage={"rightImage"}
            showcaseImage={
              <div className={classNames(defaultcss.all, sty.box__hIjlW)}>
                <img
                  alt={""}
                  className={classNames(defaultcss.img, sty.img__d33R)}
                  loading={"lazy"}
                  role={"img"}
                  src={designSystemFyeMyi6Nk}
                />
              </div>
            }
          >
            {"A system for design systems."}
          </SmallValuePropCard>
        </React.Fragment>
      }
      extras={["withExtraSlot1", "centerAligned"]}
      header={null}
      icon={null}
      slot62={
        "Whether you use Typescript or ES6, Gatsby or Next, Webpack or Parcel. Start with a single component and work up to an entire screen."
      }
      title={
        <div
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.box__xiVaE,
            {
              [sty.box__global_theme_altHeadlineFont__xiVaEfQkvX]: hasVariant(
                globalVariants,
                "theme",
                "altHeadlineFont"
              )
            }
          )}
        >
          <span>
            <React.Fragment>{"Hit the ground "}</React.Fragment>
            <span style={{ fontStyle: "italic" }}>{"running"}</span>
            <React.Fragment>{"."}</React.Fragment>
          </span>
        </div>
      }
    />
  );
}

const PlasmicDescendants = {
  root: ["root", "valueB1", "valueB42", "valueB2", "valueB4", "valueB3"],
  valueB1: ["valueB1"],
  valueB42: ["valueB42"],
  valueB2: ["valueB2"],
  valueB4: ["valueB4"],
  valueB3: ["valueB3"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicHitGroundRunningSection__ArgProps,
      internalVariantPropNames: PlasmicHitGroundRunningSection__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicHitGroundRunningSection__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHitGroundRunningSection";
  } else {
    func.displayName = `PlasmicHitGroundRunningSection.${nodeName}`;
  }
  return func;
}

export const PlasmicHitGroundRunningSection = Object.assign(
  // Top-level PlasmicHitGroundRunningSection renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    valueB1: makeNodeComponent("valueB1"),
    valueB42: makeNodeComponent("valueB42"),
    valueB2: makeNodeComponent("valueB2"),
    valueB4: makeNodeComponent("valueB4"),
    valueB3: makeNodeComponent("valueB3"),
    // Metadata about props expected for PlasmicHitGroundRunningSection
    internalVariantProps: PlasmicHitGroundRunningSection__VariantProps,
    internalArgProps: PlasmicHitGroundRunningSection__ArgProps
  }
);

export default PlasmicHitGroundRunningSection;
/* prettier-ignore-end */
