// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: kjuFFTSZb8fanzCHT2C1jz
// Component: PwVbfz5ruck
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import Header from "../../Header"; // plasmic-import: vtgKf8zu4R/component
import PageHero from "../../PageHero"; // plasmic-import: MaAtk98o9f/component
import GraphicIcon from "../../GraphicIcon"; // plasmic-import: TcXkT68Mp6/component
import ValuePropSection from "../../ValuePropSection"; // plasmic-import: 6Zq5_xjO9F/component
import Footer from "../../Footer"; // plasmic-import: 9R5YynM9KVp/component
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_plasmic_kit_website_components.module.css"; // plasmic-import: kjuFFTSZb8fanzCHT2C1jz/projectcss
import * as sty from "./PlasmicPageSiteBuilder.module.css"; // plasmic-import: PwVbfz5ruck/css
import Icon6Icon from "./icons/PlasmicIcon__Icon6"; // plasmic-import: 7p8MViVJAB/icon
import Icon10Icon from "./icons/PlasmicIcon__Icon10"; // plasmic-import: 4WWM9dCuzI/icon
import image6Zk4QpLvJs from "./images/image6.svg"; // plasmic-import: ZK4QPLv_Js/picture
import image7RU1GD3ENw from "./images/image7.svg"; // plasmic-import: rU1g-d3eNw/picture
import image2XOaQbmepj8 from "./images/image2.svg"; // plasmic-import: xOaQbmepj8/picture

export const PlasmicPageSiteBuilder__VariantProps = new Array();

export const PlasmicPageSiteBuilder__ArgProps = new Array();

function PlasmicPageSiteBuilder__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <Header
        data-plasmic-name={"header"}
        data-plasmic-override={overrides.header}
        className={classNames("__wab_instance", sty.header)}
      />

      <PageHero
        data-plasmic-name={"pageHero"}
        data-plasmic-override={overrides.pageHero}
        className={classNames("__wab_instance", sty.pageHero)}
      />

      <ValuePropSection
        backgroundImage={
          <img
            alt={""}
            className={classNames(defaultcss.img, sty.img__weTN)}
            role={"img"}
            src={image6Zk4QpLvJs}
          />
        }
        className={classNames("__wab_instance", sty.valuePropSection__pyrrZ)}
        description={
          "Keep full control how your content looks and feels in production directly from Plasmic. What you see is what you get."
        }
        header={"full control"}
        icon={
          <GraphicIcon
            className={classNames("__wab_instance", sty.graphicIcon___1IAaP)}
          >
            <Icon6Icon
              className={classNames(defaultcss.all, sty.svg___6ZDfZ)}
              role={"img"}
            />
          </GraphicIcon>
        }
        title={
          <div
            className={classNames(
              defaultcss.all,
              defaultcss.__wab_text,
              sty.box__inc0J
            )}
          >
            {"Powerful editing experience"}
          </div>
        }
      />

      <ValuePropSection
        backgroundColor={"green"}
        backgroundImage={
          <img
            alt={""}
            className={classNames(defaultcss.img, sty.img__elq)}
            role={"img"}
            src={image7RU1GD3ENw}
          />
        }
        className={classNames("__wab_instance", sty.valuePropSection___35O1F)}
        description={
          "Need to make a quick change? Publish directly from Plasmic, no need to bring up a development environment."
        }
        header={
          <div
            className={classNames(
              defaultcss.all,
              defaultcss.__wab_text,
              sty.box___89EY
            )}
          >
            {"#nocode"}
          </div>
        }
        icon={
          <GraphicIcon
            className={classNames("__wab_instance", sty.graphicIcon___0TcVn)}
            colors={"green"}
          >
            <Icon6Icon
              className={classNames(defaultcss.all, sty.svg__k77HT)}
              role={"img"}
            />
          </GraphicIcon>
        }
        title={"Zero lock-in"}
      />

      <ValuePropSection
        backgroundColor={"yellow"}
        backgroundImage={
          <img
            alt={""}
            className={classNames(defaultcss.img, sty.img__htyQb)}
            role={"img"}
            src={image2XOaQbmepj8}
          />
        }
        className={classNames("__wab_instance", sty.valuePropSection__lhwty)}
        description={
          "Iterate quickly on new designs and content and get to market faster. Ship faster, learn faster."
        }
        header={
          <div
            className={classNames(
              defaultcss.all,
              defaultcss.__wab_text,
              sty.box__lXfWk
            )}
          >
            {"#nocode"}
          </div>
        }
        icon={
          <GraphicIcon
            className={classNames("__wab_instance", sty.graphicIcon__acRek)}
            colors={"yellow"}
          >
            <Icon10Icon
              className={classNames(defaultcss.all, sty.svg__tzOYk)}
              role={"img"}
            />
          </GraphicIcon>
        }
        title={"❤️ Jamstack"}
      />

      <ValuePropSection
        backgroundColor={"orange"}
        backgroundImage={
          <img
            alt={""}
            className={classNames(defaultcss.img, sty.img__pHlv)}
            role={"img"}
            src={image7RU1GD3ENw}
          />
        }
        className={classNames("__wab_instance", sty.valuePropSection__bom2F)}
        description={
          "No need to change or replace your existing stack. Start with a blurb on a page."
        }
        header={
          <div
            className={classNames(
              defaultcss.all,
              defaultcss.__wab_text,
              sty.box__bQ4FV
            )}
          >
            {"#nocode"}
          </div>
        }
        icon={
          <GraphicIcon
            className={classNames("__wab_instance", sty.graphicIcon__uWvfM)}
          >
            <Icon6Icon
              className={classNames(defaultcss.all, sty.svg__tB408)}
              role={"img"}
            />
          </GraphicIcon>
        }
        title={"No-compromise developer control"}
      />

      <Footer
        data-plasmic-name={"footer"}
        data-plasmic-override={overrides.footer}
        className={classNames("__wab_instance", sty.footer)}
      />
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root", "header", "pageHero", "footer"],
  header: ["header"],
  pageHero: ["pageHero"],
  footer: ["footer"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicPageSiteBuilder__ArgProps,
      internalVariantPropNames: PlasmicPageSiteBuilder__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicPageSiteBuilder__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicPageSiteBuilder";
  } else {
    func.displayName = `PlasmicPageSiteBuilder.${nodeName}`;
  }
  return func;
}

export const PlasmicPageSiteBuilder = Object.assign(
  // Top-level PlasmicPageSiteBuilder renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    pageHero: makeNodeComponent("pageHero"),
    footer: makeNodeComponent("footer"),
    // Metadata about props expected for PlasmicPageSiteBuilder
    internalVariantProps: PlasmicPageSiteBuilder__VariantProps,
    internalArgProps: PlasmicPageSiteBuilder__ArgProps
  }
);

export default PlasmicPageSiteBuilder;
/* prettier-ignore-end */
