// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: kjuFFTSZb8fanzCHT2C1jz
// Component: ncmAa8DpLu
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_plasmic_kit_website_components.module.css"; // plasmic-import: kjuFFTSZb8fanzCHT2C1jz/projectcss
import * as sty from "./PlasmicFirstStepLink.module.css"; // plasmic-import: ncmAa8DpLu/css

export const PlasmicFirstStepLink__VariantProps = new Array();

export const PlasmicFirstStepLink__ArgProps = new Array(
  "children",
  "slot",
  "destination"
);

function PlasmicFirstStepLink__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  return (
    <p.Stack
      as={"a"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
      href={args.destination}
    >
      {p.renderPlasmicSlot({
        defaultContents: "Intro to Plasmic ->",
        value: args.children,
        className: classNames(sty.slotChildren)
      })}

      {p.renderPlasmicSlot({
        defaultContents: "Overview of the workflow and how it works with code.",
        value: args.slot,
        className: classNames(sty.slotSlot)
      })}
    </p.Stack>
  );
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicFirstStepLink__ArgProps,
      internalVariantPropNames: PlasmicFirstStepLink__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicFirstStepLink__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicFirstStepLink";
  } else {
    func.displayName = `PlasmicFirstStepLink.${nodeName}`;
  }
  return func;
}

export const PlasmicFirstStepLink = Object.assign(
  // Top-level PlasmicFirstStepLink renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicFirstStepLink
    internalVariantProps: PlasmicFirstStepLink__VariantProps,
    internalArgProps: PlasmicFirstStepLink__ArgProps
  }
);

export default PlasmicFirstStepLink;
/* prettier-ignore-end */
