// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: kjuFFTSZb8fanzCHT2C1jz
// Component: 6947fPy0uC
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_plasmic_kit_website_components.module.css"; // plasmic-import: kjuFFTSZb8fanzCHT2C1jz/projectcss
import * as sty from "./PlasmicTestimonialsPreviousNextButton.module.css"; // plasmic-import: 6947fPy0uC/css
import Icon2Icon from "./icons/PlasmicIcon__Icon2"; // plasmic-import: VMSgXilvsf/icon

export const PlasmicTestimonialsPreviousNextButton__VariantProps = new Array();

export const PlasmicTestimonialsPreviousNextButton__ArgProps = new Array(
  "children"
);

function PlasmicTestimonialsPreviousNextButton__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      {p.renderPlasmicSlot({
        defaultContents: (
          <Icon2Icon
            className={classNames(defaultcss.all, sty.svg__vXWxP)}
            role={"img"}
          />
        ),

        value: args.children,
        className: classNames(sty.slotChildren)
      })}
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicTestimonialsPreviousNextButton__ArgProps,
      internalVariantPropNames:
        PlasmicTestimonialsPreviousNextButton__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicTestimonialsPreviousNextButton__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicTestimonialsPreviousNextButton";
  } else {
    func.displayName = `PlasmicTestimonialsPreviousNextButton.${nodeName}`;
  }
  return func;
}

export const PlasmicTestimonialsPreviousNextButton = Object.assign(
  // Top-level PlasmicTestimonialsPreviousNextButton renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicTestimonialsPreviousNextButton
    internalVariantProps: PlasmicTestimonialsPreviousNextButton__VariantProps,
    internalArgProps: PlasmicTestimonialsPreviousNextButton__ArgProps
  }
);

export default PlasmicTestimonialsPreviousNextButton;
/* prettier-ignore-end */
