// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: HxsWCzVvbgXkQCjLyd31a
// Component: bz4oZ15QfbM9Ev
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_copy_of_code_component_examples_primary_copy.module.css"; // plasmic-import: HxsWCzVvbgXkQCjLyd31a/projectcss
import * as sty from "./PlasmicColoredSection.module.css"; // plasmic-import: bz4oZ15QfbM9Ev/css

export const PlasmicColoredSection__VariantProps = new Array();

export const PlasmicColoredSection__ArgProps = new Array("children");

function PlasmicColoredSection__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      {p.renderPlasmicSlot({
        defaultContents: null,
        value: args.children,
        className: classNames(sty.slotChildren)
      })}
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicColoredSection__ArgProps,
      internalVariantPropNames: PlasmicColoredSection__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicColoredSection__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicColoredSection";
  } else {
    func.displayName = `PlasmicColoredSection.${nodeName}`;
  }
  return func;
}

export const PlasmicColoredSection = Object.assign(
  // Top-level PlasmicColoredSection renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicColoredSection
    internalVariantProps: PlasmicColoredSection__VariantProps,
    internalArgProps: PlasmicColoredSection__ArgProps
  }
);

export default PlasmicColoredSection;
/* prettier-ignore-end */
