// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: HxsWCzVvbgXkQCjLyd31a
// Component: 4vo5LWvG1TXaVF
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_copy_of_code_component_examples_primary_copy.module.css"; // plasmic-import: HxsWCzVvbgXkQCjLyd31a/projectcss
import * as sty from "./PlasmicSectionHeading.module.css"; // plasmic-import: 4vo5LWvG1TXaVF/css

export const PlasmicSectionHeading__VariantProps = new Array();

export const PlasmicSectionHeading__ArgProps = new Array();

function PlasmicSectionHeading__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      {false ? (
        <div className={classNames(defaultcss.all, sty.box___2QBks)} />
      ) : null}

      <div
        className={classNames(
          defaultcss.all,
          defaultcss.__wab_text,
          sty.box__njlMo
        )}
      >
        {"Use off-the-shelf components."}
      </div>
    </p.Stack>
  );
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicSectionHeading__ArgProps,
      internalVariantPropNames: PlasmicSectionHeading__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicSectionHeading__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicSectionHeading";
  } else {
    func.displayName = `PlasmicSectionHeading.${nodeName}`;
  }
  return func;
}

export const PlasmicSectionHeading = Object.assign(
  // Top-level PlasmicSectionHeading renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicSectionHeading
    internalVariantProps: PlasmicSectionHeading__VariantProps,
    internalArgProps: PlasmicSectionHeading__ArgProps
  }
);

export default PlasmicSectionHeading;
/* prettier-ignore-end */
